permissionset 51100 GenPermTPE
{
    Assignable = true;
    Permissions = tabledata "Query Formula Parameter TPE" = RIMD,
        tabledata "Query Formula TPE" = RIMD,
        table "Query Formula Parameter TPE" = X,
        table "Query Formula TPE" = X,
        page "Query Formula Card TPE" = X,
        page "Query Formula List TPE" = X,
        page "Query Formula Param Sub TPE" = X,
        tabledata "Query Formula Filter TPE" = RIMD,
        table "Query Formula Filter TPE" = X,
        page "Query Formula Filter Sub TPE" = X,
        page "Query Formula Param FB TPE" = X,
        tabledata "Query Formula Execution TPE" = RIMD,
        table "Query Formula Execution TPE" = X,
        page "Query Formula Exec. List TPE" = X,
        tabledata "Query Formula Exec. Step TPE" = RIMD,
        table "Query Formula Exec. Step TPE" = X,
        page "Query Formula Lookup TPE" = X,
        page "Query Formula Param Lookup TPE" = X,
        tabledata "General Table Buffer TPE" = RIMD,
        tabledata "Query Execution Log TPE" = RIMD,
        tabledata "Special Formula TPE" = RIMD,
        table "General Table Buffer TPE" = X,
        table "Query Execution Log TPE" = X,
        table "Special Formula TPE" = X,
        codeunit "Query Executor TPE" = X,
        codeunit "Query Formula Management TPE" = X,
        codeunit "Special Formula Management TPE" = X,
        page "Date-Time Dialog TPE" = X,
        page "General Table Lookup TPE" = X,
        page "Query Formula Exec. Steps TPE" = X,
        page "Special Formula List TPE" = X;
}